import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./styles/home.module.css";
import Navbar from "./components/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Johir_Abdullah",
  description: "Generated by Johurul Amin",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.mainContainear}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
